

set(app_SOURCES
	source/Core/App.cpp
source/Core/App.h
source/Core/CameraSettings.h
source/Core/FSM.cpp
source/Core/FSM.h
source/Core/GameManager.cpp
source/Core/GameManager.h
source/Core/InputManager.cpp
source/Core/InputManager.h
source/Core/SoundManager.cpp
source/Core/SoundManager.h
source/Gameplay/BlockData.cpp
source/Gameplay/BlockData.h
source/Gameplay/BlockDataBase.cpp
source/Gameplay/BlockDataBase.h
source/Gameplay/BlockID.h
source/Gameplay/Components/InventoryComponent.cpp
source/Gameplay/Components/InventoryComponent.h
source/Gameplay/Components/LifeComponent.cpp
source/Gameplay/Components/LifeComponent.h
source/Gameplay/CraftingDataBase.cpp
source/Gameplay/CraftingDataBase.h
source/Gameplay/Enemy.cpp
source/Gameplay/Enemy.h
source/Gameplay/Entity.cpp
source/Gameplay/Entity.h
source/Gameplay/GameObject.cpp
source/Gameplay/GameObject.h
source/Gameplay/InventoryManager.cpp
source/Gameplay/InventoryManager.h
source/Gameplay/ItemData.cpp
source/Gameplay/ItemData.h
source/Gameplay/ItemDataBase.cpp
source/Gameplay/ItemDataBase.h
source/Gameplay/ItemID.h
source/Gameplay/Player.cpp
source/Gameplay/Player.h
source/Gameplay/Zombie.cpp
source/Gameplay/Zombie.h
source/main.cpp
source/Physics/Raycast.cpp
source/Physics/Raycast.h
source/Save/SaveXML.cpp
source/Save/SaveXML.h
source/States/State.h
source/States/StateMenu.cpp
source/States/StateMenu.h
source/States/StatePlay.cpp
source/States/StatePlay.h
source/UI/Settings.cpp
source/UI/Settings.h
source/UI/UI.cpp
source/UI/UI.h
source/WorldGeneration/Chunk.cpp
source/WorldGeneration/Chunk.h
source/WorldGeneration/World.cpp
source/WorldGeneration/World.h
	)
