

set(libgfx_SOURCES
	source/DataStructure/Graph.cpp
source/DataStructure/Graph.h
source/Debug/Assertion.h
source/Debug/Log.cpp
source/Debug/Log.h
source/LowRenderer/Camera.cpp
source/LowRenderer/Camera.h
source/LowRenderer/Light.cpp
source/LowRenderer/Light.h
source/LowRenderer/Model.cpp
source/LowRenderer/Model.h
source/Maths/mat3.cpp
source/Maths/mat3.h
source/Maths/mat4.cpp
source/Maths/mat4.h
source/Maths/vec2.cpp
source/Maths/vec2.h
source/Maths/vec3.cpp
source/Maths/vec3.h
source/Maths/vec4.cpp
source/Maths/vec4.h
source/Physics/Transform.cpp
source/Physics/Transform.h
source/ResourceGFX.cpp
source/ResourceGFX.h
source/Resources/LightManager.cpp
source/Resources/LightManager.h
source/Resources/Mesh.cpp
source/Resources/Mesh.h
source/Resources/ResourcesManager.cpp
source/Resources/ResourcesManager.h
source/Resources/Scene.cpp
source/Resources/Scene.h
source/Resources/Settings.h
source/Resources/Shader.cpp
source/Resources/Shader.h
source/Resources/Texture.cpp
source/Resources/Texture.h
source/Resources/TextureManager.cpp
source/Resources/TextureManager.h
	)
